### This defines a deployment for the 'cellmobs' app in the 'dev' env.  This deployment targets pods with the app label 'cellmobs'
### and env label 'dev' 
### ex: kubectl describe deployments cellmobs-react
apiVersion: apps/v1
kind: Deployment
metadata:
   labels:
      app: cellmobs-react
      env: dev
   name: cellmobs-react-dev
   namespace: cellmobs-dev
spec:
   replicas: 1
   selector:
      matchLabels:
         app: cellmobs-react
         env: dev
   template:
      metadata:
         labels:
            app: cellmobs-react
            env: dev
      spec:
         serviceAccountName: cellmobs-service-account
         containers:
         -  image: accountid.dkr.ecr.us-east-1.amazonaws.com/cellmobs-react:dev_latest
            name: cellmobs-react
            imagePullPolicy: Always
            livenessProbe:
              failureThreshold: 3
              httpGet:
                path: /health
                port: 3000
                scheme: HTTP
              periodSeconds: 60
              successThreshold: 1
              timeoutSeconds: 10
              initialDelaySeconds: 60
            readinessProbe:
              failureThreshold: 3
              httpGet:
                path: /health
                port: 3000
                scheme: HTTP
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 10
              initialDelaySeconds: 30
            resources:
               requests:
                  memory: "1000Mi"
                  cpu: "500m"
               limits:
                  memory: "2000Mi"
                  cpu: "1000m"
            env:
            -  name: X_API_KEY
               valueFrom:
                  secretKeyRef:
                     name: cellmobs-api-keys
                     key: dev
            -  name: X_TENANTID
               value: cellmobs
            -  name: API_BASE_URL
               value: https://web.cellmobs.com/v1
            -  name: HOST_NAME
               value: 
            -  name: RECAPTCHA_SITEKEY
               value: 
            -  name: GOOGLE_API_CLIENT_ID
               value: 
            -  name: TINY_MCE_KEY
               value: 
---
apiVersion: v1
### and env label 'dev'
### ex: kubectl describe services cellmobs-react
kind: Service
metadata:
   annotations:
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/backend-protocol: HTTP
   labels:
      app: cellmobs-react
      env: dev
   name: cellmobs-react-dev
   namespace: cellmobs-dev
spec:
   ports:
   -  name: 443-3000
      port: 443
      protocol: TCP
      targetPort: 3000
   selector:
      app: cellmobs-react
      env: dev
   type: NodePort
