/**
 * Reducer types
 */

export const SET_ORGANIZATION  = "SET_ORGANIZATION";
export const SET_ORGANIZATIONS  = "SET_ORGANIZATIONS";
export const SET_PAGINATION  = "SET_PAGINATION";
export const ADD_ORGANIZATION  = "ADD_ORGANIZATION";
export const REMOVE_ORGANIZATION  = "REMOVE_ORGANIZATION";
export const CLEAR_ORGANIZATION  = "CLEAR_ORGANIZATION";
export const CLEAR_ORGANIZATIONS  = "CLEAR_ORGANIZATIONS";
export const CLEAR_PAGINATION  = "CLEAR_PAGINATION";

export const SET_MEMBER  = "SET_MEMBER";
export const SET_MEMBERS  = "SET_MEMBERS";
export const SET_MEMBER_PAGINATION  = "SET_PAGINATION";
export const ADD_MEMBER  = "ADD_MEMBER";
export const REMOVE_MEMBER  = "REMOVE_MEMBER";
export const CLEAR_MEMBER  = "CLEAR_MEMBER";
export const CLEAR_MEMBERS  = "CLEAR_MEMBERS";
export const CLEAR_MEMBER_PAGINATION  = "CLEAR_PAGINATION";

export const SET_FETCHING  = "SET_FETCHING";
export const SET_ERROR  = "SET_ERROR";