/**
 * Reducer types
 */

export const SET_PRODUCT  = "SET_PRODUCT";
export const SET_PRODUCTS  = "SET_PRODUCTS";
export const SET_PAGINATION  = "SET_PAGINATION";
export const ADD_PRODUCT  = "ADD_PRODUCT";
export const REMOVE_PRODUCT  = "REMOVE_PRODUCT";
export const CLEAR_PRODUCT  = "CLEAR_PRODUCT";
export const CLEAR_PRODUCTS  = "CLEAR_PRODUCTS";
export const CLEAR_PAGINATION  = "CLEAR_PAGINATION";

export const SET_PRICE  = "SET_PRICE";
export const SET_PRICES  = "SET_PRICES";
export const SET_PRICE_PAGINATION  = "SET_PRICE_PAGINATION";
export const ADD_PRICE  = "ADD_PRICE";
export const REMOVE_PRICE  = "REMOVE_PRICE";
export const CLEAR_PRICE  = "CLEAR_PRICE";
export const CLEAR_PRICES  = "CLEAR_PRICES";
export const CLEAR_PRICE_PAGINATION  = "CLEAR_PRICE_PAGINATION";

export const SET_INVENTORY  = "SET_INVENTORY";
export const SET_INVENTORIES  = "SET_INVENTORIES";
export const SET_INVENTORY_PAGINATION  = "SET_INVENTORY_PAGINATION";
export const ADD_INVENTORY  = "ADD_INVENTORY";
export const REMOVE_INVENTORY  = "REMOVE_INVENTORY";
export const CLEAR_INVENTORY  = "CLEAR_INVENTORY";
export const CLEAR_INVENTORIES  = "CLEAR_INVENTORIES";
export const CLEAR_INVENTORY_PAGINATION  = "CLEAR_INVENTORY_PAGINATION";

export const SET_FEATURE  = "SET_FEATURE";
export const SET_FEATURES  = "SET_FEATURES";
export const SET_FEATURE_PAGINATION  = "SET_FEATURE_PAGINATION";
export const ADD_FEATURE  = "ADD_FEATURE";
export const REMOVE_FEATURE  = "REMOVE_FEATURE";
export const CLEAR_FEATURE  = "CLEAR_FEATURE";
export const CLEAR_FEATURES  = "CLEAR_FEATURES";
export const CLEAR_FEATURE_PAGINATION  = "CLEAR_FEATURE_PAGINATION";

export const SET_FETCHING  = "SET_FETCHING";
export const SET_ERROR  = "SET_ERROR";