/**
 * Reducer types
 */

export const SET_SUBSCRIPTION  = "SET_SUBSCRIPTION";
export const SET_SUBSCRIPTIONS  = "SET_SUBSCRIPTIONS";
export const SET_PAGINATION  = "SET_PAGINATION";
export const ADD_SUBSCRIPTION  = "ADD_SUBSCRIPTION";
export const REMOVE_SUBSCRIPTION  = "REMOVE_SUBSCRIPTION";
export const CLEAR_SUBSCRIPTION  = "CLEAR_SUBSCRIPTION";
export const CLEAR_SUBSCRIPTIONS  = "CLEAR_SUBSCRIPTIONS";
export const CLEAR_PAGINATION  = "CLEAR_PAGINATION";

export const SET_FETCHING  = "SET_FETCHING";
export const SET_ERROR  = "SET_ERROR";