/**
 * Reducer types
 */

export const SET_TRANSACTION  = "SET_TRANSACTION";
export const SET_TRANSACTIONS  = "SET_TRANSACTIONS";
export const SET_PAGINATION  = "SET_PAGINATION";
export const ADD_TRANSACTION  = "ADD_TRANSACTION";
export const REMOVE_TRANSACTION  = "REMOVE_TRANSACTION";
export const CLEAR_TRANSACTION  = "CLEAR_TRANSACTION";
export const CLEAR_TRANSACTIONS  = "CLEAR_TRANSACTIONS";
export const CLEAR_PAGINATION  = "CLEAR_PAGINATION";

export const SET_FETCHING  = "SET_FETCHING";
export const SET_ERROR  = "SET_ERROR";